services:
  backend:
    build: ./backend
    ports:
      - 8000:8000
    volumes:
      - ./backend/src:/app/src/
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres
    restart: always
    env_file:
      - .env
    volumes:
      - ./db:/var/lib/postgresql/
    healthcheck:
      test: ["CMD", "pg_isready", "-d", "db"]
      timeout: 20s
      retries: 10

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  frontend:
    build: ./frontend_boilerplate-main
    ports:
      - 3000:3000
    depends_on:
      - backend
    volumes:
      - ./frontend_boilerplate-main/src:/app/src/
    env_file:
      - .env
